apiVersion: v1
kind: Service
metadata:
  name: my-second-service
spec:
  selector:
    app: third-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-third-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: third-app
  template:
    metadata:
      labels:
        app: third-app
    spec:
      containers:
        - name: nodejs-db
          image: ihpar/my-db:latest 
        - name: nodejs-server
          image: ihpar/my-kub-server:latest
          env:
            - name: DB_ADDRESS
              value: localhost