apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: second-app # bu servisin hangi pod'ları servis edeceği (satır 25)
  ports:
    - port: 80
      targetPort: 3050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-second-app
spec: # deployment'a dair tanımlamalar
  replicas: 1
  selector:
    matchLabels:
      app: second-app # bu deployment'ın hangi pod'ları yöneteceği
  template: # pod ile ilgili konfig
    metadata:
      labels:
        app: second-app # istedigimiz key:value değerini verebiliriz
    spec: # pod'a dair tanımlamalar
      containers:
        - name: nodejs-db
          image: ihpar/my-db
