# https://docs.docker.com/compose/compose-file/

version: "3.8"
services:
  my-db:
    build:
      context: ./DB
      dockerfile: Dockerfile
    container_name: my-db
    image: my_db_image
  my-server:
    build: ./Server
    container_name: my-server
    image: my_server_image
    ports:
      - "80:3000"
    depends_on:
      - my-db