apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
        - name: nodejs-server
          image: ihpar/my-kub-server:latest
          env:
            - name: DB_ADDRESS
              value: "db-service.default"
