apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: second-app
  ports:
    - port: 80
      targetPort: 3050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: my-second-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template: # pod ile ilgili konfig
    metadata:
      labels:
        app: second-app # istedigimiz key:value değerini verebiliriz
    spec:
      containers:
        - name: nodejs-db
          image: ihpar/my-db